[package]
authors = ["Ceri Storey <cez@necrofish.org.uk>"]
name = "jump-ch"
version = "0.1.0"
[dependencies]
rand = "*"
xoroshiro = { version = "0.0.1", optional = true }

[dev-dependencies]
xoroshiro = "0.0.1"

[profile.release]
debug = true
[profile.bench]
debug = true
